TOPDIR = ..

OBJECTS =	SrvMsgAdvertise.o  	SrvMsgDecline.o  	SrvMsgRenew.o	  SrvMsgSolicit.o   \
		SrvMsgConfirm.o	 	SrvMsgRebind.o   	SrvMsgReply.o	  \
	 	SrvMsg.o		SrvMsgRelease.o  	SrvMsgRequest.o   SrvMsgInfRequest.o \
		SrvMsgLeaseQuery.o      SrvMsgLeaseQueryReply.o SrvMsgLeaseQueryData.o \
                SrvMsgLeaseQueryDone.o

include ../Makefile.inc

libs: libSrvMsg.a

