include ../Makefile.inc

OBJECTS = SrvOptClientIdentifier.o	SrvOptElapsed.o       SrvOptIAAddress.o      \
          SrvOptInterfaceID.o 		SrvOptPreference.o    SrvOptRapidCommit.o    \
          SrvOptServerIdentifier.o 	SrvOptServerUnicast.o SrvOptStatusCode.o     \
	  SrvOptUserClass.o 		SrvOptVendorClass.o   SrvOptVendorSpec.o     \
	  SrvOptIA_NA.o 		SrvOptOptionRequest.o SrvOptDNSServers.o     \
	  SrvOptDomainName.o        	SrvOptNTPServers.o    SrvOptTimeZone.o       \
          SrvOptSIPServer.o         	SrvOptSIPDomain.o     SrvOptFQDN.o           \
          SrvOptNISServer.o         	SrvOptNISDomain.o     SrvOptNISPServer.o     \
          SrvOptNISPDomain.o        	SrvOptLifetime.o      SrvOptTA.o             \
	  SrvOptIA_PD.o             SrvOptIAPrefix.o          SrvOptAuthentication.o
objs: $(OBJECTS)

libs: libSrvOptions.a
