include ../Makefile.inc

OBJECTS = 	SrvOptClientIdentifier.o	SrvOptElapsed.o 	SrvOptIAAddress.o  \
		SrvOptInterfaceID.o 		SrvOptPreference.o 	SrvOptRapidCommit.o \
		SrvOptServerIdentifier.o 	SrvOptServerUnicast.o 	SrvOptStatusCode.o  \
		SrvOptUserClass.o 		SrvOptVendorClass.o 	SrvOptVendorSpecInfo.o \
		SrvOptIA_NA.o 			SrvOptOptionRequest.o   SrvOptDNSServers.o \
		SrvOptDomainName.o              SrvOptNTPServers.o SrvOptTimeZone.o


objs: $(OBJECTS)

libs: libSrvOptions.a
