#define YY_ClntParser_h_included
#define YY_USE_CLASS

/*  A Bison++ parser, made from ClntParser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */

#define YY_USE_CLASS

#line 1 "../bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "../bison++/bison.cc"
#line 3 "ClntParser.y"

#include <iostream>
#include <string>
#include <malloc.h>
#include "DHCPConst.h"
#include "SmartPtr.h"
#include "Container.h"
#include "ClntParser.h"
#include "ClntParsGlobalOpt.h"
#include "ClntCfgIface.h"
#include "ClntCfgAddr.h"
#include "ClntCfgIA.h"
#include "ClntCfgTA.h"
#include "ClntCfgPD.h"
#include "ClntOptVendorSpec.h"
#include "CfgMgr.h"
#include "Logger.h"

using namespace std;
    
#define YY_USE_CLASS
#line 26 "ClntParser.y"

#include "FlexLexer.h"
#define YY_ClntParser_MEMBERS  yyFlexLexer * lex;                                          \
/*List of options in scope stack,the most fresh is last in the list*/       \
List(TClntParsGlobalOpt) ParserOptStack;			            \
/*List of parsed interfaces/IAs/Addresses, last */                          \
/*interface/IA/address is just being parsing or have been just parsed*/     \
List(TClntCfgIface) ClntCfgIfaceLst;	                                    \
List(TClntCfgIA)    ClntCfgIALst;		                            \
List(TClntCfgTA)    ClntCfgTALst;                                           \
List(TClntCfgPD)    ClntCfgPDLst;                                           \
List(TClntCfgAddr)  ClntCfgAddrLst;                                         \
/*Pointer to list which should contain either rejected servers or */        \
/*preffered servers*/                                                       \
TContainer<SmartPtr<TStationID> > PresentStationLst;                        \
TContainer<SmartPtr<TIPv6Addr> > PresentAddrLst;                            \
TContainer<SmartPtr<string> > PresentStringLst;                             \
List(TClntOptVendorSpec) VendorSpec;					    \
/*method check whether interface with id=ifaceNr has been */                \
/*already declared */                                                       \
bool CheckIsIface(int ifaceNr);                                             \
/* method check if interface with id=ifaceName has been already declared */ \
bool CheckIsIface(string ifaceName);                                        \
void StartIfaceDeclaration();                                               \
bool EndIfaceDeclaration();                                                 \
void EmptyIface();                                                          \
void StartIADeclaration(bool aggregation);                                  \
void EndIADeclaration();                                                    \
void StartPDDeclaration();                                                  \
bool EndPDDeclaration();                                                    \
void EmptyIA();                                                             \
void EmptyAddr();                                                           \
bool iaidSet;                                                               \
unsigned int iaid;                                                          \
virtual ~ClntParser();                                                      \
EDUIDType DUIDType;
#define YY_ClntParser_CONSTRUCTOR_PARAM  yyFlexLexer * lex
#define YY_ClntParser_CONSTRUCTOR_CODE                                                     \
    this->lex = lex;                                                        \
    ParserOptStack.append(new TClntParsGlobalOpt());                        \
    ParserOptStack.getFirst()->setIAIDCnt(1);                               \
    ParserOptStack.getLast();                                               \
    DUIDType = DUID_TYPE_NOT_DEFINED;

#line 75 "ClntParser.y"
typedef union    
{
    int ival;    
    char *strval;  
    struct SDuid  {      
        int length;    
        char* duid;  
    } duidval;  
    char addrval[16];  
} yy_ClntParser_stype;
#define YY_ClntParser_STYPE yy_ClntParser_stype
#line 86 "ClntParser.y"

namespace std
{
    extern yy_ClntParser_stype yylval;
}

#line 88 "../bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_ClntParser_BISON 1

#ifndef YY_ClntParser_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_ClntParser_COMPATIBILITY 1
 #else
  #define  YY_ClntParser_COMPATIBILITY 0
 #endif
#endif

#if YY_ClntParser_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_ClntParser_LTYPE
   #define YY_ClntParser_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_ClntParser_STYPE 
   #define YY_ClntParser_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_ClntParser_DEBUG
   #define  YY_ClntParser_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_ClntParser_USE_GOTO
  #define YY_ClntParser_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_ClntParser_USE_GOTO
 #define YY_ClntParser_USE_GOTO 0
#endif

#ifndef YY_ClntParser_PURE

 #line 130 "../bison++/bison.cc"

#line 130 "../bison++/bison.cc"
/*  YY_ClntParser_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "../bison++/bison.cc"

#line 134 "../bison++/bison.cc"
/* prefix */
#ifndef YY_ClntParser_DEBUG

 #line 136 "../bison++/bison.cc"

#line 136 "../bison++/bison.cc"
/* YY_ClntParser_DEBUG */
#endif


#ifndef YY_ClntParser_LSP_NEEDED

 #line 141 "../bison++/bison.cc"

#line 141 "../bison++/bison.cc"
 /* YY_ClntParser_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_ClntParser_LSP_NEEDED
#ifndef YY_ClntParser_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_ClntParser_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_ClntParser_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_ClntParser_STYPE
#define YY_ClntParser_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_ClntParser_PARSE
#define YY_ClntParser_PARSE yyparse
#endif
#ifndef YY_ClntParser_LEX
#define YY_ClntParser_LEX yylex
#endif
#ifndef YY_ClntParser_LVAL
#define YY_ClntParser_LVAL yylval
#endif
#ifndef YY_ClntParser_LLOC
#define YY_ClntParser_LLOC yylloc
#endif
#ifndef YY_ClntParser_CHAR
#define YY_ClntParser_CHAR yychar
#endif
#ifndef YY_ClntParser_NERRS
#define YY_ClntParser_NERRS yynerrs
#endif
#ifndef YY_ClntParser_DEBUG_FLAG
#define YY_ClntParser_DEBUG_FLAG yydebug
#endif
#ifndef YY_ClntParser_ERROR
#define YY_ClntParser_ERROR yyerror
#endif

#ifndef YY_ClntParser_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_ClntParser_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_ClntParser_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_ClntParser_PARSE_PARAM
  #define YY_ClntParser_PARSE_PARAM void
 #endif
#endif

#if YY_ClntParser_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_ClntParser_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_ClntParser_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_ClntParser_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_ClntParser_PURE
#  ifndef YYPURE
#    define YYPURE YY_ClntParser_PURE
#  endif
#endif

#ifdef YY_ClntParser_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_ClntParser_DEBUG 
#  endif
#endif

#ifndef YY_ClntParser_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_ClntParser_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_ClntParser_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_ClntParser_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "../bison++/bison.cc"
#define	T1_	258
#define	T2_	259
#define	PREF_TIME_	260
#define	DNS_SERVER_	261
#define	VALID_TIME_	262
#define	UNICAST_	263
#define	NTP_SERVER_	264
#define	DOMAIN_	265
#define	TIME_ZONE_	266
#define	SIP_SERVER_	267
#define	SIP_DOMAIN_	268
#define	NIS_SERVER_	269
#define	NISP_SERVER_	270
#define	NIS_DOMAIN_	271
#define	NISP_DOMAIN_	272
#define	FQDN_	273
#define	LIFETIME_	274
#define	VENDOR_SPEC_	275
#define	IFACE_	276
#define	NO_CONFIG_	277
#define	REJECT_SERVERS_	278
#define	PREFERRED_SERVERS_	279
#define	IA_	280
#define	TA_	281
#define	IAID_	282
#define	ADDRES_	283
#define	IPV6ADDR_	284
#define	WORKDIR_	285
#define	RAPID_COMMIT_	286
#define	STATELESS_	287
#define	OPTION_	288
#define	SCRIPTS_DIR_	289
#define	LOGNAME_	290
#define	LOGLEVEL_	291
#define	LOGMODE_	292
#define	STRING_	293
#define	HEXNUMBER_	294
#define	INTNUMBER_	295
#define	DUID_	296
#define	STRICT_RFC_NO_ROUTING_	297
#define	PD_	298
#define	DUID_TYPE_	299
#define	DUID_TYPE_LLT_	300
#define	DUID_TYPE_LL_	301
#define	DUID_TYPE_EN_	302
#define	AUTH_	303
#define	DIGEST_NONE_	304
#define	DIGEST_HMAC_SHA1_	305


#line 263 "../bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_ClntParser_CLASS
#define YY_ClntParser_CLASS ClntParser
#endif
#ifndef YY_ClntParser_INHERIT
#define YY_ClntParser_INHERIT
#endif
#ifndef YY_ClntParser_MEMBERS
#define YY_ClntParser_MEMBERS 
#endif
#ifndef YY_ClntParser_LEX_BODY
#define YY_ClntParser_LEX_BODY  
#endif
#ifndef YY_ClntParser_ERROR_BODY
#define YY_ClntParser_ERROR_BODY  
#endif
#ifndef YY_ClntParser_CONSTRUCTOR_PARAM
#define YY_ClntParser_CONSTRUCTOR_PARAM
#endif
#ifndef YY_ClntParser_CONSTRUCTOR_CODE
#define YY_ClntParser_CONSTRUCTOR_CODE
#endif
#ifndef YY_ClntParser_CONSTRUCTOR_INIT
#define YY_ClntParser_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_ClntParser_USE_CONST_TOKEN
#define YY_ClntParser_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_ClntParser_USE_CONST_TOKEN != 0
#ifndef YY_ClntParser_ENUM_TOKEN
#define YY_ClntParser_ENUM_TOKEN yy_ClntParser_enum_token
#endif
#endif

class YY_ClntParser_CLASS YY_ClntParser_INHERIT
{
public: 
#if YY_ClntParser_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "../bison++/bison.cc"
static const int T1_;
static const int T2_;
static const int PREF_TIME_;
static const int DNS_SERVER_;
static const int VALID_TIME_;
static const int UNICAST_;
static const int NTP_SERVER_;
static const int DOMAIN_;
static const int TIME_ZONE_;
static const int SIP_SERVER_;
static const int SIP_DOMAIN_;
static const int NIS_SERVER_;
static const int NISP_SERVER_;
static const int NIS_DOMAIN_;
static const int NISP_DOMAIN_;
static const int FQDN_;
static const int LIFETIME_;
static const int VENDOR_SPEC_;
static const int IFACE_;
static const int NO_CONFIG_;
static const int REJECT_SERVERS_;
static const int PREFERRED_SERVERS_;
static const int IA_;
static const int TA_;
static const int IAID_;
static const int ADDRES_;
static const int IPV6ADDR_;
static const int WORKDIR_;
static const int RAPID_COMMIT_;
static const int STATELESS_;
static const int OPTION_;
static const int SCRIPTS_DIR_;
static const int LOGNAME_;
static const int LOGLEVEL_;
static const int LOGMODE_;
static const int STRING_;
static const int HEXNUMBER_;
static const int INTNUMBER_;
static const int DUID_;
static const int STRICT_RFC_NO_ROUTING_;
static const int PD_;
static const int DUID_TYPE_;
static const int DUID_TYPE_LLT_;
static const int DUID_TYPE_LL_;
static const int DUID_TYPE_EN_;
static const int AUTH_;
static const int DIGEST_NONE_;
static const int DIGEST_HMAC_SHA1_;


#line 307 "../bison++/bison.cc"
 /* decl const */
#else
enum YY_ClntParser_ENUM_TOKEN { YY_ClntParser_NULL_TOKEN=0

 #line 310 "../bison++/bison.cc"
	,T1_=258
	,T2_=259
	,PREF_TIME_=260
	,DNS_SERVER_=261
	,VALID_TIME_=262
	,UNICAST_=263
	,NTP_SERVER_=264
	,DOMAIN_=265
	,TIME_ZONE_=266
	,SIP_SERVER_=267
	,SIP_DOMAIN_=268
	,NIS_SERVER_=269
	,NISP_SERVER_=270
	,NIS_DOMAIN_=271
	,NISP_DOMAIN_=272
	,FQDN_=273
	,LIFETIME_=274
	,VENDOR_SPEC_=275
	,IFACE_=276
	,NO_CONFIG_=277
	,REJECT_SERVERS_=278
	,PREFERRED_SERVERS_=279
	,IA_=280
	,TA_=281
	,IAID_=282
	,ADDRES_=283
	,IPV6ADDR_=284
	,WORKDIR_=285
	,RAPID_COMMIT_=286
	,STATELESS_=287
	,OPTION_=288
	,SCRIPTS_DIR_=289
	,LOGNAME_=290
	,LOGLEVEL_=291
	,LOGMODE_=292
	,STRING_=293
	,HEXNUMBER_=294
	,INTNUMBER_=295
	,DUID_=296
	,STRICT_RFC_NO_ROUTING_=297
	,PD_=298
	,DUID_TYPE_=299
	,DUID_TYPE_LLT_=300
	,DUID_TYPE_LL_=301
	,DUID_TYPE_EN_=302
	,AUTH_=303
	,DIGEST_NONE_=304
	,DIGEST_HMAC_SHA1_=305


#line 310 "../bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_ClntParser_PARSE (YY_ClntParser_PARSE_PARAM);
 virtual void YY_ClntParser_ERROR(char *msg) YY_ClntParser_ERROR_BODY;
#ifdef YY_ClntParser_PURE
#ifdef YY_ClntParser_LSP_NEEDED
 virtual int  YY_ClntParser_LEX (YY_ClntParser_STYPE *YY_ClntParser_LVAL,YY_ClntParser_LTYPE *YY_ClntParser_LLOC) YY_ClntParser_LEX_BODY;
#else
 virtual int  YY_ClntParser_LEX (YY_ClntParser_STYPE *YY_ClntParser_LVAL) YY_ClntParser_LEX_BODY;
#endif
#else
 virtual int YY_ClntParser_LEX() YY_ClntParser_LEX_BODY;
 YY_ClntParser_STYPE YY_ClntParser_LVAL;
#ifdef YY_ClntParser_LSP_NEEDED
 YY_ClntParser_LTYPE YY_ClntParser_LLOC;
#endif
 int   YY_ClntParser_NERRS;
 int    YY_ClntParser_CHAR;
#endif
#if YY_ClntParser_DEBUG != 0
 int YY_ClntParser_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_ClntParser_CLASS(YY_ClntParser_CONSTRUCTOR_PARAM);
public:
 YY_ClntParser_MEMBERS 
};
/* other declare folow */
#if YY_ClntParser_USE_CONST_TOKEN != 0

 #line 341 "../bison++/bison.cc"
const int YY_ClntParser_CLASS::T1_=258;
const int YY_ClntParser_CLASS::T2_=259;
const int YY_ClntParser_CLASS::PREF_TIME_=260;
const int YY_ClntParser_CLASS::DNS_SERVER_=261;
const int YY_ClntParser_CLASS::VALID_TIME_=262;
const int YY_ClntParser_CLASS::UNICAST_=263;
const int YY_ClntParser_CLASS::NTP_SERVER_=264;
const int YY_ClntParser_CLASS::DOMAIN_=265;
const int YY_ClntParser_CLASS::TIME_ZONE_=266;
const int YY_ClntParser_CLASS::SIP_SERVER_=267;
const int YY_ClntParser_CLASS::SIP_DOMAIN_=268;
const int YY_ClntParser_CLASS::NIS_SERVER_=269;
const int YY_ClntParser_CLASS::NISP_SERVER_=270;
const int YY_ClntParser_CLASS::NIS_DOMAIN_=271;
const int YY_ClntParser_CLASS::NISP_DOMAIN_=272;
const int YY_ClntParser_CLASS::FQDN_=273;
const int YY_ClntParser_CLASS::LIFETIME_=274;
const int YY_ClntParser_CLASS::VENDOR_SPEC_=275;
const int YY_ClntParser_CLASS::IFACE_=276;
const int YY_ClntParser_CLASS::NO_CONFIG_=277;
const int YY_ClntParser_CLASS::REJECT_SERVERS_=278;
const int YY_ClntParser_CLASS::PREFERRED_SERVERS_=279;
const int YY_ClntParser_CLASS::IA_=280;
const int YY_ClntParser_CLASS::TA_=281;
const int YY_ClntParser_CLASS::IAID_=282;
const int YY_ClntParser_CLASS::ADDRES_=283;
const int YY_ClntParser_CLASS::IPV6ADDR_=284;
const int YY_ClntParser_CLASS::WORKDIR_=285;
const int YY_ClntParser_CLASS::RAPID_COMMIT_=286;
const int YY_ClntParser_CLASS::STATELESS_=287;
const int YY_ClntParser_CLASS::OPTION_=288;
const int YY_ClntParser_CLASS::SCRIPTS_DIR_=289;
const int YY_ClntParser_CLASS::LOGNAME_=290;
const int YY_ClntParser_CLASS::LOGLEVEL_=291;
const int YY_ClntParser_CLASS::LOGMODE_=292;
const int YY_ClntParser_CLASS::STRING_=293;
const int YY_ClntParser_CLASS::HEXNUMBER_=294;
const int YY_ClntParser_CLASS::INTNUMBER_=295;
const int YY_ClntParser_CLASS::DUID_=296;
const int YY_ClntParser_CLASS::STRICT_RFC_NO_ROUTING_=297;
const int YY_ClntParser_CLASS::PD_=298;
const int YY_ClntParser_CLASS::DUID_TYPE_=299;
const int YY_ClntParser_CLASS::DUID_TYPE_LLT_=300;
const int YY_ClntParser_CLASS::DUID_TYPE_LL_=301;
const int YY_ClntParser_CLASS::DUID_TYPE_EN_=302;
const int YY_ClntParser_CLASS::AUTH_=303;
const int YY_ClntParser_CLASS::DIGEST_NONE_=304;
const int YY_ClntParser_CLASS::DIGEST_HMAC_SHA1_=305;


#line 341 "../bison++/bison.cc"
 /* const YY_ClntParser_CLASS::token */
#endif
/*apres const  */
YY_ClntParser_CLASS::YY_ClntParser_CLASS(YY_ClntParser_CONSTRUCTOR_PARAM) YY_ClntParser_CONSTRUCTOR_INIT
{
#if YY_ClntParser_DEBUG != 0
YY_ClntParser_DEBUG_FLAG=0;
#endif
YY_ClntParser_CONSTRUCTOR_CODE;
}
#endif

 #line 352 "../bison++/bison.cc"


#define	YYFINAL		199
#define	YYFLAG		-32768
#define	YYNTBASE	54

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 124)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    53,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    51,     2,    52,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_ClntParser_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     5,     7,    10,    13,    15,    17,    19,
    21,    23,    25,    27,    29,    31,    33,    35,    37,    39,
    41,    43,    45,    47,    49,    51,    53,    55,    57,    59,
    61,    63,    65,    67,    69,    71,    73,    75,    76,    83,
    84,    91,    96,   101,   105,   109,   111,   114,   116,   119,
   121,   124,   126,   129,   131,   132,   133,   140,   144,   147,
   149,   152,   153,   159,   163,   165,   167,   170,   172,   175,
   176,   182,   183,   190,   195,   199,   202,   204,   206,   209,
   211,   214,   216,   218,   221,   224,   227,   230,   233,   236,
   239,   241,   244,   246,   249,   252,   255,   256,   260,   261,
   265,   268,   271,   274,   277,   280,   282,   286,   287,   293,
   295,   298,   300,   302,   305,   307,   309,   313,   317,   319,
   323,   325,   329,   331,   333,   336,   337,   342,   345,   346,
   351,   354,   355,   360,   363,   367,   370,   371,   376,   379,
   380,   385,   388,   392,   395,   396,   401,   404,   405,   410,
   413,   417,   420,   424,   427,   430,   435,   439,   441
};

static const short yyrhs[] = {    55,
     0,     0,    56,     0,    59,     0,    55,    56,     0,    55,
    59,     0,    57,     0,    77,     0,    78,     0,    76,     0,
    81,     0,    79,     0,    82,     0,    83,     0,    84,     0,
    58,     0,    80,     0,    98,     0,   103,     0,   105,     0,
   107,     0,   109,     0,   110,     0,   112,     0,   114,     0,
   115,     0,   117,     0,   119,     0,   120,     0,   121,     0,
   122,     0,    85,     0,    87,     0,    92,     0,    93,     0,
    90,     0,    75,     0,     0,    21,    38,    51,    60,    62,
    52,     0,     0,    21,   102,    51,    61,    62,    52,     0,
    21,    38,    51,    52,     0,    21,   102,    51,    52,     0,
    21,    38,    22,     0,    21,   102,    22,     0,    57,     0,
    62,    57,     0,    68,     0,    62,    68,     0,    63,     0,
    62,    63,     0,    94,     0,    62,    94,     0,    26,     0,
     0,     0,    26,    51,    64,    66,    65,    52,     0,    26,
    51,    52,     0,    66,    67,     0,    67,     0,    27,   102,
     0,     0,    25,    51,    69,    70,    52,     0,    25,    51,
    52,     0,    25,     0,    58,     0,    70,    58,     0,    71,
     0,    70,    71,     0,     0,    28,    51,    72,    74,    52,
     0,     0,    28,   102,    51,    73,    74,    52,     0,    28,
   102,    51,    52,     0,    28,    51,    52,     0,    28,   102,
     0,    28,     0,    75,     0,    74,    75,     0,    29,     0,
    74,    29,     0,    89,     0,    91,     0,    36,   102,     0,
    37,    38,     0,    35,    38,     0,    44,   102,     0,    44,
    45,     0,    44,    46,     0,    44,    47,     0,    32,     0,
    30,    38,     0,    42,     0,    34,    38,     0,    48,    49,
     0,    48,    50,     0,     0,    23,    86,    99,     0,     0,
    24,    88,    99,     0,     5,   102,     0,    31,   102,     0,
     7,   102,     0,     3,   102,     0,     4,   102,     0,    43,
     0,    43,    51,    52,     0,     0,    43,    51,    95,    96,
    52,     0,    97,     0,    96,    97,     0,    92,     0,    93,
     0,     8,   102,     0,    29,     0,    41,     0,    99,    53,
    29,     0,    99,    53,    41,     0,    29,     0,   100,    53,
    29,     0,    38,     0,   101,    53,    38,     0,    39,     0,
    40,     0,    33,     6,     0,     0,    33,     6,   104,   100,
     0,    33,    10,     0,     0,    33,    10,   106,   101,     0,
    33,     9,     0,     0,    33,     9,   108,   100,     0,    33,
    11,     0,    33,    11,    38,     0,    33,    12,     0,     0,
    33,    12,   111,   100,     0,    33,    13,     0,     0,    33,
    13,   113,   101,     0,    33,    18,     0,    33,    18,    38,
     0,    33,    14,     0,     0,    33,    14,   116,   100,     0,
    33,    15,     0,     0,    33,    15,   118,   100,     0,    33,
    16,     0,    33,    16,    38,     0,    33,    17,     0,    33,
    17,    38,     0,    33,    19,     0,    33,    20,     0,    33,
    20,   102,    41,     0,    33,    20,   123,     0,   102,     0,
   123,    53,   102,     0
};

#endif

#if (YY_ClntParser_DEBUG != 0) || defined(YY_ClntParser_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   120,   121,   125,   126,   127,   128,   132,   133,   134,   135,
   136,   137,   138,   139,   140,   144,   145,   146,   147,   148,
   149,   150,   151,   152,   153,   154,   155,   156,   157,   158,
   159,   160,   161,   165,   166,   167,   168,   175,   180,   194,
   199,   209,   220,   230,   242,   255,   256,   257,   258,   259,
   260,   261,   262,   269,   274,   281,   287,   287,   295,   296,
   300,   312,   316,   324,   333,   341,   342,   343,   344,   348,
   354,   363,   368,   374,   379,   384,   389,   396,   397,   398,
   408,   421,   422,   426,   436,   441,   446,   455,   456,   457,
   461,   468,   475,   484,   490,   491,   494,   499,   505,   508,
   515,   522,   529,   536,   543,   550,   556,   562,   566,   573,
   574,   578,   579,   583,   601,   605,   609,   613,   620,   621,
   625,   626,   629,   630,   637,   643,   647,   656,   661,   664,
   673,   679,   682,   691,   695,   705,   711,   714,   723,   728,
   731,   740,   744,   754,   760,   763,   772,   778,   781,   790,
   794,   805,   809,   819,   826,   832,   838,   846,   847
};

static const char * const yytname[] = {   "$","error","$illegal.","T1_","T2_",
"PREF_TIME_","DNS_SERVER_","VALID_TIME_","UNICAST_","NTP_SERVER_","DOMAIN_",
"TIME_ZONE_","SIP_SERVER_","SIP_DOMAIN_","NIS_SERVER_","NISP_SERVER_","NIS_DOMAIN_",
"NISP_DOMAIN_","FQDN_","LIFETIME_","VENDOR_SPEC_","IFACE_","NO_CONFIG_","REJECT_SERVERS_",
"PREFERRED_SERVERS_","IA_","TA_","IAID_","ADDRES_","IPV6ADDR_","WORKDIR_","RAPID_COMMIT_",
"STATELESS_","OPTION_","SCRIPTS_DIR_","LOGNAME_","LOGLEVEL_","LOGMODE_","STRING_",
"HEXNUMBER_","INTNUMBER_","DUID_","STRICT_RFC_NO_ROUTING_","PD_","DUID_TYPE_",
"DUID_TYPE_LLT_","DUID_TYPE_LL_","DUID_TYPE_EN_","AUTH_","DIGEST_NONE_","DIGEST_HMAC_SHA1_",
"'{'","'}'","','","Grammar","GlobalDeclarationList","GlobalOptionDeclaration",
"InterfaceOptionDeclaration","IAOptionDeclaration","InterfaceDeclaration","@1",
"@2","InterfaceDeclarationsList","TADeclaration","@3","@4","TADeclarationList",
"IAID","IADeclaration","@5","IADeclarationList","ADDRESDeclaration","@6","@7",
"ADDRESDeclarationList","ADDRESOptionDeclaration","LogLevelOption","LogModeOption",
"LogNameOption","DuidTypeOption","NoIAsOptions","WorkDirOption","StrictRfcNoRoutingOption",
"ScriptsDir","AuthOption","RejectServersOption","@8","PreferServersOption","@9",
"PreferredTimeOption","RapidCommitOption","ValidTimeOption","T1Option","T2Option",
"PDDeclaration","@10","PDOptionsList","PDOption","UnicastOption","ADDRESDUIDList",
"ADDRESSList","StringList","Number","DNSServerOption","@11","DomainOption","@12",
"NTPServerOption","@13","TimeZoneOption","SIPServerOption","@14","SIPDomainOption",
"@15","FQDNOption","NISServerOption","@16","NISPServerOption","@17","NISDomainOption",
"NISPDomainOption","LifetimeOption","VendorSpecOption","VendorSpecList",""
};
#endif

static const short yyr1[] = {     0,
    54,    54,    55,    55,    55,    55,    56,    56,    56,    56,
    56,    56,    56,    56,    56,    57,    57,    57,    57,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    57,    57,
    57,    57,    57,    58,    58,    58,    58,    60,    59,    61,
    59,    59,    59,    59,    59,    62,    62,    62,    62,    62,
    62,    62,    62,    63,    64,    65,    63,    63,    66,    66,
    67,    69,    68,    68,    68,    70,    70,    70,    70,    72,
    71,    73,    71,    71,    71,    71,    71,    74,    74,    74,
    74,    75,    75,    76,    77,    78,    79,    79,    79,    79,
    80,    81,    82,    83,    84,    84,    86,    85,    88,    87,
    89,    90,    91,    92,    93,    94,    94,    95,    94,    96,
    96,    97,    97,    98,    99,    99,    99,    99,   100,   100,
   101,   101,   102,   102,   103,   104,   103,   105,   106,   105,
   107,   108,   107,   109,   109,   110,   111,   110,   112,   113,
   112,   114,   114,   115,   116,   115,   117,   118,   117,   119,
   119,   120,   120,   121,   122,   122,   122,   123,   123
};

static const short yyr2[] = {     0,
     1,     0,     1,     1,     2,     2,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     0,     6,     0,
     6,     4,     4,     3,     3,     1,     2,     1,     2,     1,
     2,     1,     2,     1,     0,     0,     6,     3,     2,     1,
     2,     0,     5,     3,     1,     1,     2,     1,     2,     0,
     5,     0,     6,     4,     3,     2,     1,     1,     2,     1,
     2,     1,     1,     2,     2,     2,     2,     2,     2,     2,
     1,     2,     1,     2,     2,     2,     0,     3,     0,     3,
     2,     2,     2,     2,     2,     1,     3,     0,     5,     1,
     2,     1,     1,     2,     1,     1,     3,     3,     1,     3,
     1,     3,     1,     1,     2,     0,     4,     2,     0,     4,
     2,     0,     4,     2,     3,     2,     0,     4,     2,     0,
     4,     2,     3,     2,     0,     4,     2,     0,     4,     2,
     3,     2,     3,     2,     2,     4,     3,     1,     3
};

static const short yydefact[] = {     2,
     0,     0,     0,     0,     0,     0,    97,    99,     0,     0,
    91,     0,     0,     0,     0,     0,    93,     0,     0,     1,
     3,     7,    16,     4,    37,    10,     8,     9,    12,    17,
    11,    13,    14,    15,    32,    33,    82,    36,    83,    34,
    35,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    28,    29,    30,    31,   123,   124,   104,   105,   101,
   103,   114,     0,     0,     0,     0,    92,   102,   125,   131,
   128,   134,   136,   139,   144,   147,   150,   152,   142,   154,
   155,    94,    86,    84,    85,    88,    89,    90,    87,    95,
    96,     5,     6,    44,    38,    45,    40,   115,   116,    98,
   100,     0,     0,     0,   135,     0,     0,     0,     0,   151,
   153,   143,   158,   157,    42,     0,    43,     0,     0,   119,
   127,   133,   121,   130,   138,   141,   146,   149,   156,     0,
    65,    54,   106,    46,     0,    50,    48,    52,     0,   117,
   118,     0,     0,   159,    62,    55,   108,    39,    47,    51,
    49,    53,    41,   120,   122,    64,     0,    58,     0,   107,
     0,    77,    66,     0,    68,     0,    56,    60,   112,   113,
     0,   110,    70,    76,    63,    67,    69,    61,     0,    59,
   109,   111,    75,     0,    72,    57,    80,     0,    78,    74,
     0,    81,    71,    79,     0,    73,     0,     0,     0
};

static const short yydefgoto[] = {   197,
    20,    21,    22,    23,    24,   116,   118,   135,   136,   159,
   179,   167,   168,   137,   157,   164,   165,   184,   191,   188,
    25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
    35,    65,    36,    66,    37,    38,    39,    40,    41,   138,
   161,   171,   172,    42,   100,   121,   124,    58,    43,   102,
    44,   104,    45,   103,    46,    47,   106,    48,   107,    49,
    50,   108,    51,   109,    52,    53,    54,    55,   114
};

static const short yypact[] = {    79,
    16,    16,    16,    16,    16,    67,-32768,-32768,   -23,    16,
-32768,   161,    27,    38,    16,    54,-32768,   101,    76,    79,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    -8,    10,   -12,   -12,-32768,-32768,    70,    88,
    56,    81,   106,    99,   124,   125,   117,   118,   123,-32768,
    16,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   110,-32768,   111,-32768,-32768,    55,
    55,   136,   136,   128,-32768,   136,   128,   136,   136,-32768,
-32768,-32768,   127,   129,-32768,   126,-32768,   126,    -5,-32768,
   130,   130,-32768,   131,   130,   131,   130,   130,-32768,    16,
   134,   135,   137,-32768,     2,-32768,-32768,-32768,    15,-32768,
-32768,   158,   151,-32768,   138,   139,   140,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    65,-32768,   166,-32768,
   141,    24,-32768,    46,-32768,    16,   166,-32768,-32768,-32768,
     8,-32768,   142,   144,-32768,-32768,-32768,-32768,   145,-32768,
-32768,-32768,-32768,    66,   146,-32768,-32768,    37,-32768,-32768,
    66,-32768,-32768,-32768,    52,-32768,   196,   199,-32768
};

static const short yypgoto[] = {-32768,
-32768,   180,   -38,  -127,   181,-32768,-32768,    84,   -17,-32768,
-32768,-32768,    36,   -15,-32768,-32768,    40,-32768,-32768,    14,
   -52,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,  -140,  -109,     3,
-32768,-32768,    35,-32768,   143,   -18,   100,    -2,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768
};


#define	YYLAST		209


static const short yytable[] = {    59,
    60,    61,    62,    64,     1,     2,     3,    68,     4,     5,
     1,     2,    84,    94,    67,    89,    98,     1,     2,     3,
   169,     4,     5,   140,     7,     8,   131,   132,    99,   163,
   169,    96,    10,    11,    12,   141,   176,     7,     8,   131,
   132,     3,    95,     4,   133,    10,    11,    12,     1,     2,
     3,   170,     4,   148,    56,    57,     3,   133,     4,   181,
    97,   170,    56,    57,    82,   192,   153,     1,     2,     3,
     3,     4,     4,   162,   173,    83,    10,   134,   113,   134,
   192,     1,     2,     3,   122,     4,     5,   125,   193,   127,
   128,    85,   162,  -129,   187,    10,   149,   175,  -126,     6,
   149,     7,     8,   196,    63,    56,    57,   119,     9,    10,
    11,    12,    13,    14,    15,    16,  -132,   150,   105,   151,
    17,   150,    18,   151,    90,    91,    19,   144,     1,     2,
     3,   189,     4,     5,  -137,   194,  -140,   152,   189,    56,
    57,   152,   194,     1,     2,    86,    87,    88,     7,     8,
   131,   132,  -145,  -148,   110,   111,    10,    11,    12,   174,
   112,   115,   117,   178,   120,   123,    69,   129,   133,    70,
    71,    72,    73,    74,    75,    76,    77,    78,    79,    80,
    81,   130,   142,   143,   145,   146,   154,   147,   155,   156,
   158,   160,   166,   183,   185,   198,   186,   190,   199,    92,
    93,   139,   180,   177,   195,   182,   126,     0,   101
};

static const short yycheck[] = {     2,
     3,     4,     5,     6,     3,     4,     5,    10,     7,     8,
     3,     4,    15,    22,    38,    18,    29,     3,     4,     5,
   161,     7,     8,    29,    23,    24,    25,    26,    41,   157,
   171,    22,    31,    32,    33,    41,   164,    23,    24,    25,
    26,     5,    51,     7,    43,    31,    32,    33,     3,     4,
     5,   161,     7,    52,    39,    40,     5,    43,     7,    52,
    51,   171,    39,    40,    38,    29,    52,     3,     4,     5,
     5,     7,     7,    28,    51,    38,    31,   116,    81,   118,
    29,     3,     4,     5,   103,     7,     8,   106,    52,   108,
   109,    38,    28,    38,    29,    31,   135,    52,    29,    21,
   139,    23,    24,    52,    38,    39,    40,    53,    30,    31,
    32,    33,    34,    35,    36,    37,    29,   135,    38,   135,
    42,   139,    44,   139,    49,    50,    48,   130,     3,     4,
     5,   184,     7,     8,    29,   188,    38,   135,   191,    39,
    40,   139,   195,     3,     4,    45,    46,    47,    23,    24,
    25,    26,    29,    29,    38,    38,    31,    32,    33,   162,
    38,    52,    52,   166,    29,    38,     6,    41,    43,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    53,    53,    53,    51,    51,    29,    51,    38,    52,
    52,    52,    27,    52,    51,     0,    52,    52,     0,    20,
    20,   118,   167,   164,   191,   171,   107,    -1,    66
};

#line 352 "../bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_ClntParser_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  }
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL  
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_ClntParser_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_ClntParser_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_ClntParser_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_ClntParser_CHAR = (token), YY_ClntParser_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_ClntParser_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_ClntParser_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_ClntParser_PURE
/* UNPURE */
#define YYLEX           YY_ClntParser_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_ClntParser_CHAR;                      /*  the lookahead symbol        */
YY_ClntParser_STYPE      YY_ClntParser_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_ClntParser_NERRS;                 /*  number of parse errors so far */
#ifdef YY_ClntParser_LSP_NEEDED
YY_ClntParser_LTYPE YY_ClntParser_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_ClntParser_LSP_NEEDED
#define YYLEX           YY_ClntParser_LEX(&YY_ClntParser_LVAL, &YY_ClntParser_LLOC)
#else
#define YYLEX           YY_ClntParser_LEX(&YY_ClntParser_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_ClntParser_DEBUG != 0
int YY_ClntParser_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_ClntParser_CLASS::
#endif
     YY_ClntParser_PARSE(YY_ClntParser_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_ClntParser_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_ClntParser_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_ClntParser_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_ClntParser_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_ClntParser_LSP_NEEDED
  YY_ClntParser_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_ClntParser_LTYPE *yyls = yylsa;
  YY_ClntParser_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_ClntParser_PURE
  int YY_ClntParser_CHAR;
  YY_ClntParser_STYPE YY_ClntParser_LVAL;
  int YY_ClntParser_NERRS;
#ifdef YY_ClntParser_LSP_NEEDED
  YY_ClntParser_LTYPE YY_ClntParser_LLOC;
#endif
#endif

  YY_ClntParser_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_ClntParser_NERRS = 0;
  YY_ClntParser_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_ClntParser_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_ClntParser_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_ClntParser_LSP_NEEDED
      YY_ClntParser_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_ClntParser_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_ClntParser_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_ClntParser_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_ClntParser_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_ClntParser_LSP_NEEDED
      yyls = (YY_ClntParser_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_ClntParser_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_ClntParser_DEBUG != 0
      if (YY_ClntParser_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_ClntParser_CHAR == YYEMPTY)
    {
#if YY_ClntParser_DEBUG != 0
      if (YY_ClntParser_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_ClntParser_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_ClntParser_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_ClntParser_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_ClntParser_DEBUG != 0
      if (YY_ClntParser_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_ClntParser_CHAR);

#if YY_ClntParser_DEBUG != 0
      if (YY_ClntParser_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_ClntParser_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_ClntParser_CHAR, YY_ClntParser_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_ClntParser_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_ClntParser_CHAR != YYEOF)
    YY_ClntParser_CHAR = YYEMPTY;

  *++yyvsp = YY_ClntParser_LVAL;
#ifdef YY_ClntParser_LSP_NEEDED
  *++yylsp = YY_ClntParser_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "../bison++/bison.cc"

  switch (yyn) {

case 38:
#line 176 "ClntParser.y"
{
    CheckIsIface(string(yyvsp[-1].strval)); //If no - everything is ok
    StartIfaceDeclaration();
;
    break;}
case 39:
#line 181 "ClntParser.y"
{
    //Information about new interface has been read
    //Add it to list of read interfaces
    ClntCfgIfaceLst.append(new TClntCfgIface(yyvsp[-4].strval));
    //FIXME:used of char * should be always realeased
    delete [] yyvsp[-4].strval;
    if (!EndIfaceDeclaration())
	YYABORT;
;
    break;}
case 40:
#line 195 "ClntParser.y"
{
    CheckIsIface(yyvsp[-1].ival);   //If no - everything is ok
    StartIfaceDeclaration();
;
    break;}
case 41:
#line 200 "ClntParser.y"
{
    ClntCfgIfaceLst.append(new TClntCfgIface(yyvsp[-4].ival) );
    if (!EndIfaceDeclaration())
	YYABORT;
;
    break;}
case 42:
#line 210 "ClntParser.y"
{
    CheckIsIface(string(yyvsp[-2].strval));
    ClntCfgIfaceLst.append(new TClntCfgIface(yyvsp[-2].strval));
    delete [] yyvsp[-2].strval;
    EmptyIface();
;
    break;}
case 43:
#line 221 "ClntParser.y"
{
    CheckIsIface(yyvsp[-2].ival);
    ClntCfgIfaceLst.append(new TClntCfgIface(yyvsp[-2].ival));
    EmptyIface();
;
    break;}
case 44:
#line 231 "ClntParser.y"
{
    CheckIsIface(string(yyvsp[-1].strval));
    ClntCfgIfaceLst.append(new TClntCfgIface(yyvsp[-1].strval));
    ClntCfgIfaceLst.getLast()->setOptions(ParserOptStack.getLast());
    ClntCfgIfaceLst.getLast()->setNoConfig();
    delete yyvsp[-1].strval;
;
    break;}
case 45:
#line 243 "ClntParser.y"
{
    CheckIsIface(yyvsp[-1].ival);
    ClntCfgIfaceLst.append(SmartPtr<TClntCfgIface> (new TClntCfgIface(yyvsp[-1].ival)) );
    ClntCfgIfaceLst.getLast()->setOptions(ParserOptStack.getLast());
    ClntCfgIfaceLst.getLast()->setNoConfig();
;
    break;}
case 54:
#line 270 "ClntParser.y"
{ 
    //Log(Crit) << "TA without params." << LogEnd;
    this->ClntCfgTALst.append( new TClntCfgTA() ); // append new TA
;
    break;}
case 55:
#line 275 "ClntParser.y"
{
    //Log(Crit) << "TA with params started." << LogEnd;
    this->ClntCfgTALst.append( new TClntCfgTA() ); // append new TA
    this->iaidSet = false;
;
    break;}
case 56:
#line 281 "ClntParser.y"
{
    if (this->iaidSet)
	this->ClntCfgTALst.getLast()->setIAID(this->iaid);
    //Log(Crit) << "TA with params ended." << LogEnd;
;
    break;}
case 58:
#line 288 "ClntParser.y"
{
    //Log(Crit) << "TA without params." << LogEnd;
    this->ClntCfgTALst.append( new TClntCfgTA() ); // append new TA
;
    break;}
case 61:
#line 301 "ClntParser.y"
{
    this->iaidSet = true;
    this->iaid = yyvsp[0].ival;
    Log(Crit) << "IAID=" << this->iaid << " parsed." << LogEnd;
;
    break;}
case 62:
#line 313 "ClntParser.y"
{ 
    StartIADeclaration(false);
;
    break;}
case 63:
#line 317 "ClntParser.y"
{
    EndIADeclaration();
;
    break;}
case 64:
#line 325 "ClntParser.y"
{
    StartIADeclaration(true);
    EndIADeclaration();
;
    break;}
case 65:
#line 334 "ClntParser.y"
{
    StartIADeclaration(true);
    EndIADeclaration();
;
    break;}
case 70:
#line 349 "ClntParser.y"
{
    SmartPtr<TClntParsGlobalOpt> globalOpt = ParserOptStack.getLast();
    SmartPtr<TClntParsGlobalOpt> newOpt = new TClntParsGlobalOpt(*globalOpt);
    ParserOptStack.append(newOpt);
;
    break;}
case 71:
#line 355 "ClntParser.y"
{
    //ClntCfgAddrLst.append(SmartPtr<TClntCfgAddr> (new TClntCfgAddr()));
    //set proper options specific for this Address
    //ClntCfgAddrLst.getLast()->setOptions(&(*ParserOptStack.getLast()));
    if (ParserOptStack.count())
	ParserOptStack.delLast();
;
    break;}
case 72:
#line 364 "ClntParser.y"
{
    ParserOptStack.append(new TClntParsGlobalOpt(*ParserOptStack.getLast()));
    ParserOptStack.getLast()->setAddrHint(false);
;
    break;}
case 73:
#line 369 "ClntParser.y"
{
    for (int i=0;i<yyvsp[-4].ival; i++) EmptyAddr();
    ParserOptStack.delLast();
;
    break;}
case 74:
#line 375 "ClntParser.y"
{
    for (int i=0;i<yyvsp[-2].ival; i++) EmptyAddr();
;
    break;}
case 75:
#line 380 "ClntParser.y"
{
    EmptyAddr();
;
    break;}
case 76:
#line 385 "ClntParser.y"
{
    for (int i=0;i<yyvsp[0].ival; i++) EmptyAddr();
;
    break;}
case 77:
#line 390 "ClntParser.y"
{
    EmptyAddr();
;
    break;}
case 80:
#line 399 "ClntParser.y"
{
    if (ParserOptStack.getLast()->getAddrHint())
    {
        ClntCfgAddrLst.append(new TClntCfgAddr(new TIPv6Addr(yyvsp[0].addrval)));
        ClntCfgAddrLst.getLast()->setOptions(ParserOptStack.getLast());
    }
    else
	YYABORT;  //this is aggregated version of IA
;
    break;}
case 81:
#line 409 "ClntParser.y"
{
    if (ParserOptStack.getLast()->getAddrHint())
    {
	ClntCfgAddrLst.append(new TClntCfgAddr(new TIPv6Addr(yyvsp[0].addrval)));
	ClntCfgAddrLst.getLast()->setOptions(ParserOptStack.getLast());
    }
    else
	YYABORT; //here is agregated version of IA
;
    break;}
case 84:
#line 427 "ClntParser.y"
{
    if ( (yyvsp[0].ival<1) || (yyvsp[0].ival>8) ) {
	Log(Crit) << "Invalid loglevel specified: " << yyvsp[0].ival << ". Allowed range: 1-8." << LogEnd;
    }
    logger::setLogLevel(yyvsp[0].ival);
;
    break;}
case 85:
#line 436 "ClntParser.y"
{
    logger::setLogMode(yyvsp[0].strval);
;
    break;}
case 86:
#line 441 "ClntParser.y"
{
    logger::setLogName(yyvsp[0].strval);
;
    break;}
case 87:
#line 447 "ClntParser.y"
{ 
    if ( ((yyvsp[0].ival)>DUID_TYPE_NOT_DEFINED) && ((yyvsp[0].ival)<=DUID_TYPE_LL) ) {
	this->DUIDType=(EDUIDType)(yyvsp[0].ival); 
    } else {
	Log(Error) << "Invalid DUID type (" << yyvsp[0].ival << ") specifed in the configuration file." << LogEnd;
	YYABORT;
    }
;
    break;}
case 88:
#line 455 "ClntParser.y"
{ this->DUIDType  = DUID_TYPE_LLT;;
    break;}
case 89:
#line 456 "ClntParser.y"
{ this->DUIDType  = DUID_TYPE_LL; ;
    break;}
case 90:
#line 457 "ClntParser.y"
{ this->DUIDType  = DUID_TYPE_EN; ;
    break;}
case 91:
#line 462 "ClntParser.y"
{
    ParserOptStack.getLast()->setIsIAs(false);
;
    break;}
case 92:
#line 469 "ClntParser.y"
{
    ParserOptStack.getLast()->setWorkDir(yyvsp[0].strval);
;
    break;}
case 93:
#line 476 "ClntParser.y"
{
    Log(Notice) << "Strict-rfc-no-routing directive set: addresses will be added with 128 prefix." << LogEnd;
    ParserOptStack.getLast()->setPrefixLength(128);
    // by default prefix is set to 128
;
    break;}
case 94:
#line 485 "ClntParser.y"
{
    ParserOptStack.getLast()->setScriptsDir(yyvsp[0].strval);
;
    break;}
case 95:
#line 490 "ClntParser.y"
{ ParserOptStack.getLast()->setDigest(DIGEST_NONE); ;
    break;}
case 96:
#line 491 "ClntParser.y"
{ ParserOptStack.getLast()->setDigest(DIGEST_HMAC_SHA1); ;
    break;}
case 97:
#line 495 "ClntParser.y"
{
    //ParserOptStack.getLast()->clearRejedSrv();
    PresentStationLst.clear();
;
    break;}
case 98:
#line 499 "ClntParser.y"
{
    ParserOptStack.getLast()->setRejedSrvLst(&PresentStationLst);
;
    break;}
case 99:
#line 506 "ClntParser.y"
{
    PresentStationLst.clear();
;
    break;}
case 100:
#line 508 "ClntParser.y"
{
    ParserOptStack.getLast()->setPrefSrvLst(&PresentStationLst);
;
    break;}
case 101:
#line 516 "ClntParser.y"
{
    ParserOptStack.getLast()->setPref(yyvsp[0].ival);
;
    break;}
case 102:
#line 523 "ClntParser.y"
{ 
    ParserOptStack.getLast()->setRapidCommit(yyvsp[0].ival);
;
    break;}
case 103:
#line 530 "ClntParser.y"
{
    ParserOptStack.getLast()->setValid(yyvsp[0].ival);
;
    break;}
case 104:
#line 537 "ClntParser.y"
{
    ParserOptStack.getLast()->setT1(yyvsp[0].ival);
;
    break;}
case 105:
#line 544 "ClntParser.y"
{
    ParserOptStack.getLast()->setT2(yyvsp[0].ival);
;
    break;}
case 106:
#line 551 "ClntParser.y"
{
    Log(Debug) << "Prefix delegation option found." << LogEnd;
    StartPDDeclaration();
    EndPDDeclaration();
;
    break;}
case 107:
#line 557 "ClntParser.y"
{
    Log(Debug) << "Prefix delegation option found." << LogEnd;
    StartPDDeclaration();
    EndPDDeclaration();
;
    break;}
case 108:
#line 563 "ClntParser.y"
{
    StartPDDeclaration();
;
    break;}
case 109:
#line 567 "ClntParser.y"
{
    EndPDDeclaration();
;
    break;}
case 114:
#line 584 "ClntParser.y"
{
    switch(yyvsp[0].ival) {
    case 0:
	ParserOptStack.getLast()->setUnicast(false);
	break;
    case 1:
	ParserOptStack.getLast()->setUnicast(true);
	break;
    default:
	Log(Error) << "Invalid parameter (" << yyvsp[0].ival << ") passed to unicast in line " 
		   << lex->YYText() << "." << LogEnd;
	return 1;
    }
;
    break;}
case 115:
#line 602 "ClntParser.y"
{
    PresentStationLst.append(SmartPtr<TStationID> (new TStationID(new TIPv6Addr(yyvsp[0].addrval))));
;
    break;}
case 116:
#line 606 "ClntParser.y"
{
    PresentStationLst.append(SmartPtr<TStationID> (new TStationID(new TDUID(yyvsp[0].duidval.duid,yyvsp[0].duidval.length))));
;
    break;}
case 117:
#line 610 "ClntParser.y"
{
    PresentStationLst.append(SmartPtr<TStationID> (new TStationID(new TIPv6Addr(yyvsp[0].addrval))));
;
    break;}
case 118:
#line 614 "ClntParser.y"
{
    PresentStationLst.append(SmartPtr<TStationID> (new TStationID( new TDUID(yyvsp[0].duidval.duid,yyvsp[0].duidval.length))));
;
    break;}
case 119:
#line 620 "ClntParser.y"
{PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr(yyvsp[0].addrval)));;
    break;}
case 120:
#line 621 "ClntParser.y"
{PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr(yyvsp[0].addrval)));;
    break;}
case 121:
#line 625 "ClntParser.y"
{ PresentStringLst.append(SmartPtr<string> (new string(yyvsp[0].strval))); ;
    break;}
case 122:
#line 626 "ClntParser.y"
{ PresentStringLst.append(SmartPtr<string> (new string(yyvsp[0].strval))); ;
    break;}
case 123:
#line 629 "ClntParser.y"
{yyval.ival=yyvsp[0].ival;;
    break;}
case 124:
#line 630 "ClntParser.y"
{yyval.ival=yyvsp[0].ival;;
    break;}
case 125:
#line 638 "ClntParser.y"
{
    PresentAddrLst.clear();
//    PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr()));
    ParserOptStack.getLast()->setDNSServerLst(&PresentAddrLst);
;
    break;}
case 126:
#line 644 "ClntParser.y"
{
    PresentAddrLst.clear();
;
    break;}
case 127:
#line 647 "ClntParser.y"
{
    ParserOptStack.getLast()->setDNSServerLst(&PresentAddrLst);
;
    break;}
case 128:
#line 657 "ClntParser.y"
{
    PresentStringLst.clear();
    ParserOptStack.getLast()->setDomainLst(&PresentStringLst);
;
    break;}
case 129:
#line 661 "ClntParser.y"
{ 
    PresentStringLst.clear();
;
    break;}
case 130:
#line 664 "ClntParser.y"
{
    ParserOptStack.getLast()->setDomainLst(&PresentStringLst);
;
    break;}
case 131:
#line 674 "ClntParser.y"
{
    PresentAddrLst.clear();
//    PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr()));
    ParserOptStack.getLast()->setNTPServerLst(&PresentAddrLst);
;
    break;}
case 132:
#line 679 "ClntParser.y"
{
    PresentAddrLst.clear();
;
    break;}
case 133:
#line 682 "ClntParser.y"
{
    ParserOptStack.getLast()->setNTPServerLst(&PresentAddrLst);
;
    break;}
case 134:
#line 692 "ClntParser.y"
{
    ParserOptStack.getLast()->setTimezone(string(""));
  ;
    break;}
case 135:
#line 696 "ClntParser.y"
{
    ParserOptStack.getLast()->setTimezone(yyvsp[0].strval);
;
    break;}
case 136:
#line 706 "ClntParser.y"
{
    PresentAddrLst.clear();
//    PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr()));
    ParserOptStack.getLast()->setSIPServerLst(&PresentAddrLst);
;
    break;}
case 137:
#line 711 "ClntParser.y"
{
    PresentAddrLst.clear();
;
    break;}
case 138:
#line 714 "ClntParser.y"
{
    ParserOptStack.getLast()->setSIPServerLst(&PresentAddrLst);
;
    break;}
case 139:
#line 724 "ClntParser.y"
{
    PresentStringLst.clear();
    ParserOptStack.getLast()->setSIPDomainLst(&PresentStringLst);
;
    break;}
case 140:
#line 728 "ClntParser.y"
{
    PresentStringLst.clear();
;
    break;}
case 141:
#line 731 "ClntParser.y"
{
    ParserOptStack.getLast()->setSIPDomainLst(&PresentStringLst);
;
    break;}
case 142:
#line 741 "ClntParser.y"
{
    ParserOptStack.getLast()->setFQDN(string(""));
;
    break;}
case 143:
#line 745 "ClntParser.y"
{
    ParserOptStack.getLast()->setFQDN(yyvsp[0].strval);
;
    break;}
case 144:
#line 755 "ClntParser.y"
{
    PresentAddrLst.clear();
//    PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr()));
    ParserOptStack.getLast()->setNISServerLst(&PresentAddrLst);
;
    break;}
case 145:
#line 760 "ClntParser.y"
{
    PresentAddrLst.clear();
;
    break;}
case 146:
#line 763 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISServerLst(&PresentAddrLst);
;
    break;}
case 147:
#line 773 "ClntParser.y"
{
    PresentAddrLst.clear();
//    PresentAddrLst.append(SmartPtr<TIPv6Addr> (new TIPv6Addr()));
    ParserOptStack.getLast()->setNISPServerLst(&PresentAddrLst);
;
    break;}
case 148:
#line 778 "ClntParser.y"
{
    PresentAddrLst.clear();
;
    break;}
case 149:
#line 781 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISPServerLst(&PresentAddrLst);
;
    break;}
case 150:
#line 791 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISDomain("");
;
    break;}
case 151:
#line 795 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISDomain(yyvsp[0].strval);
;
    break;}
case 152:
#line 806 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISPDomain("");
;
    break;}
case 153:
#line 810 "ClntParser.y"
{
    ParserOptStack.getLast()->setNISPDomain(yyvsp[0].strval);
;
    break;}
case 154:
#line 820 "ClntParser.y"
{
    ParserOptStack.getLast()->setLifetime();
;
    break;}
case 155:
#line 827 "ClntParser.y"
{
    Log(Debug) << "VendorSpec defined (no details)." << LogEnd;
    ParserOptStack.getLast()->setVendorSpec();
    this->VendorSpec.clear();
;
    break;}
case 156:
#line 833 "ClntParser.y"
{
    Log(Debug) << "VendorSpec defined (enterprise=" << yyvsp[-1].ival << ", hint data length=" << yyvsp[0].duidval.length << ")." << LogEnd;
    ParserOptStack.getLast()->setVendorSpec();
    this->VendorSpec.append(new TClntOptVendorSpec(yyvsp[-1].ival, yyvsp[0].duidval.duid, yyvsp[0].duidval.length, 0));
;
    break;}
case 157:
#line 839 "ClntParser.y"
{
    ParserOptStack.getLast()->setVendorSpec();
    Log(Debug) << "VendorSpec defined (multiple times)." << LogEnd;
;
    break;}
case 158:
#line 846 "ClntParser.y"
{ VendorSpec.append( new TClntOptVendorSpec(yyvsp[0].ival,0,0,0) ); ;
    break;}
case 159:
#line 847 "ClntParser.y"
{ VendorSpec.append( new TClntOptVendorSpec(yyvsp[0].ival,0,0,0) ); ;
    break;}
}

#line 839 "../bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_ClntParser_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_ClntParser_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_ClntParser_LLOC.first_line;
      yylsp->first_column = YY_ClntParser_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_ClntParser_NERRS;

#ifdef YY_ClntParser_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_ClntParser_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_ClntParser_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_ClntParser_ERROR_VERBOSE */
	YY_ClntParser_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_ClntParser_CHAR == YYEOF)
	YYABORT;

#if YY_ClntParser_DEBUG != 0
      if (YY_ClntParser_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_ClntParser_CHAR, yytname[yychar1]);
#endif

      YY_ClntParser_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_ClntParser_LSP_NEEDED
  yylsp--;
#endif

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_ClntParser_DEBUG != 0
  if (YY_ClntParser_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_ClntParser_LVAL;
#ifdef YY_ClntParser_LSP_NEEDED
  *++yylsp = YY_ClntParser_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "../bison++/bison.cc"
#line 851 "ClntParser.y"


/////////////////////////////////////////////////////////////////////////////
// programs section
/////////////////////////////////////////////////////////////////////////////

//
/** 
 * method check whether interface with id=ifaceNr has been 
 * already declared. YYABORT macro is called to abort parsing.
 * 
 * @param ifaceNr 
 * 
 * @return true if not declared.
 */bool ClntParser::CheckIsIface(int ifaceNr)
{
  SmartPtr<TClntCfgIface> ptr;
  ClntCfgIfaceLst.first();
  while (ptr=ClntCfgIfaceLst.get())
    if ((ptr->getID())==ifaceNr) YYABORT;
  return true;
}
    
//method check whether interface with id=ifaceName has been
//already declared 
bool ClntParser::CheckIsIface(string ifaceName)
{
  SmartPtr<TClntCfgIface> ptr;
  ClntCfgIfaceLst.first();
  while (ptr=ClntCfgIfaceLst.get())
  {
    string presName=ptr->getName();
    if (presName==ifaceName) YYABORT;
  };
  return true;
}

/** 
 * creates new scope appropriately for interface options and declarations
 * clears all lists except the list of interfaces and adds new group
 */
void ClntParser::StartIfaceDeclaration()
{
  //Interface scope, so parameters associated with global scope are pushed on stack
  ParserOptStack.append(new TClntParsGlobalOpt(*ParserOptStack.getLast()));
  ClntCfgIALst.clear();
  ClntCfgAddrLst.clear();
  this->VendorSpec.clear();
}

bool ClntParser::EndIfaceDeclaration()
{
    SmartPtr<TClntCfgIface> iface = ClntCfgIfaceLst.getLast();
    if (!iface) {
	Log(Crit) << "Internal error: Interface not found. Something is wrong. Very wrong." << LogEnd;
	return false;
    }

    // set interface options on the basis of just read information
    // preferred-server and rejected-servers are also copied here
    if (VendorSpec.count())
	ParserOptStack.getLast()->setVendorSpec(VendorSpec);
    iface->setOptions(ParserOptStack.getLast());
    iface->setPrefixLength(ParserOptStack.getLast()->getPrefixLength());

    if ( (iface->stateless()) && (ClntCfgIALst.count()) ) {
	Log(Crit) << "Interface " << iface->getFullName() << " is configured stateless, "
	    " but has " << ClntCfgIALst.count() << " IA(s) defined." << LogEnd;
	return false;
    }

    if ( (iface->stateless()) && (ClntCfgTALst.count()) ) {
	Log(Crit) << "Interface " << iface->getFullName() << " is configured stateless, "
	    " but has TA defined." << LogEnd;
	return false;
    }

    // add all IAs to the interface
    SmartPtr<TClntCfgIA> ia;
    ClntCfgIALst.first();
    while (ia=ClntCfgIALst.get()) {
	ClntCfgIfaceLst.getLast()->addIA(ia);
    }
    
    //add all TAs to the interface
    SmartPtr<TClntCfgTA> ptrTA;
    ClntCfgTALst.first();
    while ( ptrTA = ClntCfgTALst.get() ) {
	iface->addTA(ptrTA);
    }

    //add all PDs to the interface
    SPtr<TClntCfgPD> pd;
    ClntCfgPDLst.first();
    while (pd = ClntCfgPDLst.get() ) {
	iface->addPD(pd);
    }

    //restore global options
    ParserOptStack.delLast();
    ClntCfgIALst.clear();
    return true;
}   

void ClntParser::EmptyIface()
{
    //set iface options on the basis of recent information
    ClntCfgIfaceLst.getLast()->setOptions(ParserOptStack.getLast());
    //add one IA with one address to this iface
    EmptyIA();
    ClntCfgIALst.getLast()->setOptions(ParserOptStack.getLast());
    ClntCfgIfaceLst.getLast()->addIA(ClntCfgIALst.getLast());
}

/** 
 * method creates new scope appropriately for interface options and declarations
 * clears list of addresses
 * 
 * @param aggregation - does this IA contains suboptions ( ia { ... } )
 */
void ClntParser::StartIADeclaration(bool aggregation)
{
  ParserOptStack.append(new TClntParsGlobalOpt(*ParserOptStack.getLast()));
  ParserOptStack.getLast()->setAddrHint(!aggregation);
  ClntCfgAddrLst.clear();
}

/** 
 * Inbelivable piece of crap code. If you read this, rewrite this code immediately.
 * 
 */
void ClntParser::EndIADeclaration()
{
    if(!ClntCfgAddrLst.count()) {
	EmptyIA();
    } else {
	SmartPtr<TClntCfgIA> ia = new TClntCfgIA();
	ClntCfgIALst.append(ia);
	SmartPtr<TClntCfgAddr> ptr;
	ClntCfgAddrLst.first();
	while(ptr=ClntCfgAddrLst.get())
	    ia->addAddr(ptr);
    }

    //set proper options specific for this IA
    ClntCfgIALst.getLast()->setOptions(ParserOptStack.getLast());

    ClntCfgAddrLst.clear();
    ParserOptStack.delLast();

    //this IA matches with previous ones and can be grouped with them
    //so it's should be left on the list and be appended with them to present list
}

void ClntParser::StartPDDeclaration()
{
  ParserOptStack.append(new TClntParsGlobalOpt(*ParserOptStack.getLast()));
  ClntCfgAddrLst.clear();
}

bool ClntParser::EndPDDeclaration()
{
    SPtr<TClntCfgPD> pd = new TClntCfgPD();
    pd->setOptions(ParserOptStack.getLast());
    ClntCfgPDLst.append(pd);
    ParserOptStack.delLast();
    return true;
}

/** 
 * method adds 1 IA object (containing 1 address) to the ClntCfgIA list.
 * Both objects' properties are set to last parsed values
 * 
 */void ClntParser::EmptyIA()
{
    EmptyAddr();
    ClntCfgIALst.append(new TClntCfgIA());
    ClntCfgIALst.getLast()->setOptions(ParserOptStack.getLast());
    //ClntCfgIALst.getLast()->addAddr(ClntCfgAddrLst.getLast());
}   

/** 
 * method adds empty address to the ClntCfgAddrList list and sets
 * its properties to last parsed values
 * 
 */
void ClntParser::EmptyAddr()
{
    ClntCfgAddrLst.append(new TClntCfgAddr());
    ClntCfgAddrLst.getLast()->setOptions(ParserOptStack.getLast());
}   


int ClntParser::yylex()
{
    memset(&std::yylval,0, sizeof(std::yylval));
    memset(&this->yylval,0, sizeof(this->yylval));
    int x = this->lex->yylex();
    this->yylval=std::yylval;
    return x;
}

/** 
 * This method is called when parsing error is detected.
 * 
 * @param m - first invalid character
 */
void ClntParser::yyerror(char *m)
{
    Log(Crit) << "Config parse error: line " << lex->lineno() 
	      << ", unexpected [" << lex->YYText() << "] token." << LogEnd;
}

/** 
 * Desctructor. Just cleans things up
 * 
 */

ClntParser::~ClntParser() {
    this->ClntCfgIfaceLst.clear();
    this->ClntCfgIALst.clear();
    this->ClntCfgTALst.clear();
    this->ClntCfgAddrLst.clear();
}
