include ../Makefile.inc

OBJECTS = ClntOptClientIdentifier.o 	ClntOptElapsed.o 	ClntOptIAAddress.o      \
	  ClntOptInterfaceID.o 		ClntOptPreference.o 	ClntOptRapidCommit.o    \
	  ClntOptServerIdentifier.o 	ClntOptServerUnicast.o 	ClntOptStatusCode.o 	\
	  ClntOptUserClass.o 		ClntOptVendorClass.o 	ClntOptVendorSpecInfo.o \
	  ClntOptIA_NA.o		ClntOptOptionRequest.o  ClntOptDNSServers.o     \
	  ClntOptDomainName.o		ClntOptNTPServers.o     ClntOptTimeZone.o

objs: $(OBJECTS)

libs: libClntOptions.a

