include ../Makefile.inc

OBJECTS = Opt.o               OptElapsed.o       OptIAAddress.o                               \
	  OptPreference.o     OptRapidCommit.o       OptInteger4.o      OptDUID.o             \
	  OptStatusCode.o     OptUserClass.o         OptVendorClass.o   OptVendorSpecInfo.o   \
	  OptIA_NA.o          OptOptionRequest.o     OptAddr.o          OptAddrLst.o          \
	  OptString.o         OptStringLst.o         OptGeneric.o       OptTA.o

objs: $(OBJECTS)

libs: libOptions.a
