include ../Makefile.inc

OBJECTS = Opt.o               OptClientIdentifier.o  OptElapsed.o       OptIAAddress.o        \
	  OptInterfaceID.o    OptPreference.o        OptRapidCommit.o   OptServerIdentifier.o \
	  OptStatusCode.o     OptUserClass.o         OptVendorClass.o   OptVendorSpecInfo.o   \
          OptIA_NA.o          OptOptionRequest.o     OptAddr.o          OptAddrLst.o          \
          OptString.o         OptStringLst.o         OptInteger4.o

objs: $(OBJECTS)

libs: libOptions.a
