include ../Makefile.inc

OBJECTS = Opt.o               OptClientIdentifier.o  OptElapsed.o       OptIAAddress.o        \
	  OptInterfaceID.o    OptPreference.o        OptRapidCommit.o   OptServerIdentifier.o \
	  OptServerUnicast.o  OptStatusCode.o        OptUserClass.o     OptVendorClass.o      \
          OptVendorSpecInfo.o OptIA_NA.o             OptOptionRequest.o	OptDNSServers.o       \
          OptDomainName.o     OptNTPServers.o        OptTimeZone.o

objs: $(OBJECTS)

libs: libOptions.a
