TOPDIR = ..
OBJECTS =       ClntMsgAdvertise.o  	ClntMsgDecline.o  	ClntMsgRenew.o     \
		ClntMsgSolicit.o   	ClntMsgConfirm.o	ClntMsgRebind.o    \
		ClntMsgReply.o	  	ClntMsgInfRequest.o  	ClntMsg.o          \
		ClntMsgRelease.o        ClntMsgRequest.o        

include $(TOPDIR)/Makefile.inc

libs: libClntMsg.a
