include ../Makefile.inc

OBJECTS =       ClntMsgAdvertise.o  	ClntMsgDecline.o  	ClntMsgRenew.o     \
		ClntMsgSolicit.o   	ClntMsgConfirm.o	ClntMsgRebind.o    \
		ClntMsgReply.o	  	ClntMsgInfRequest.o  	ClntMsg.o          \
		ClntMsgRelease.o        ClntMsgRequest.o        

objs: $(OBJECTS)

libs: libClntMsg.a
